#!/bin/sh

case "$1" in
    "")
        if cc -o bip bip.c; then
            ./bip && nsxiv --anti-alias=no *.bmp
        fi
        ;;
    "run")
        ./bip && nsxiv --anti-alias=no *.bmp
        ;;
    "clean")
        rm *.bmp bip
        ;;
esac
