#!/bin/sh

runner () {
    local os="$(uname)"

    case "$os" in
        "Darwin") ./bip && open -a Preview *.bmp ;;
        "Linux") ./bip && nsxiv --anti-alias=no *.bmp ;;
    esac
}

case "$1" in
    "") cc -o bip bip.c && runner ;;
    "run") runner ;;
    "clean") rm *.bmp bip ;;
esac
