#!/bin/sh

#############################################################
## bip - algorithmic image generator           B. R. Shellito 

os="$(uname)"

finder () {
    find . -maxdepth 1 -type f \( -iname '*.bmp' -o -iname '*.xpm' \)
}

runner () {
    ./bip "$@"

    images=$(finder)

    case "$os" in
        "Darwin")
            open $images
            ;;
        *)
            if command -v nsxiv >/dev/null 2>&1; then
                nsxiv --anti-alias=no $images
            elif command -v feh >/dev/null 2>&1; then
                feh --force-aliasing $images
            else
                xdg-open $images
            fi
            ;;
    esac
}

runner "$@"
