#!/bin/sh

#######################################################
## bip image generator                B. R. Shellito ##
##                                                   ##
## script to open an image after bip generates it    ##
## the case for macos just uses preview because it   ##
## knows not to apply anti aliasing for bmp files    ##
## the rest of the script tries several common foss  ##
## image viewing apps with flags for disabling anti  ##
## aliasing, and if none are found, then it falls    ##
## back to xdg-open                                  ##
##                                                   ##
#######################################################

os="$(uname)"

case "$os" in
    "Darwin") bip && open -a Preview *.bmp ;;
    *)
        bip
        if command -v nsxiv >/dev/null 2>&1; then
            nsxiv --anti-alias=no *.bmp
        elif command -v feh >/dev/null 2>&1; then
            feh *.bmp
        elif command -v imv >/dev/null 2>&1; then
            imv -s *.bmp
        elif command -v swayimg >/dev/null 2>&1; then
            swayimg --antialiasing none *.bmp
        else
            xdg-open *.bmp
        fi
esac
