#!/bin/sh

os="$(uname)"
[ "$os" = "Darwin" ] && "$HOME/.local/scripts/nukeds"

git add .
git commit -m "[ ${*} ][ $(date '+%a_%y%m%d ][ %I:%M%p' | tr '[:upper:]' '[:lower:]') ][ $USER ]"
git push -u origin master
